"""Public metric helpers kept for backward-compatible imports."""

from ticker_analyzer.metrics.builder import (
    apply_configured_metric_fallbacks,
    build_charts_data,
    build_raw_metrics,
)
from ticker_analyzer.metrics.formulas import (
    accruals_ratio_observations,
    build_fundamentals_metrics,
    cfo_to_debt,
    debt_to_assets,
    equity_to_assets,
    fcf_margin_observations,
    free_cash_flow_series,
    gross_margin_trend,
    interest_coverage,
    is_financial_company,
    net_debt_to_ebitda_observations,
    net_margin,
    ohlson_probability,
    operating_margin,
    quick_ratio,
    quick_ratio_median,
    quick_ratio_observations,
    quick_ratio_range_metric,
    return_on_assets,
    return_on_equity,
    roic_observations,
    share_count_cagr,
)
from ticker_analyzer.metrics.utils import (
    aligned_ratio_observations,
    cagr_pct,
    clean_number,
    latest_row_value,
    latest_statement_growth,
    median_or_none,
    metric_value,
    momentum_12_1,
    percent_change,
    percentage_change_from_history,
    range_median_note,
    range_ratio_metric,
    row_values,
    scale_billions,
    statement_ratio_median,
    statement_ratio_observations,
    statement_value_years_ago,
    sum_recent,
    sum_window,
    ttm_range_cagr,
    value_on_or_before,
)
from ticker_analyzer.metrics.valuation import (
    HistoricalRatioContext,
    approximate_historical_ratio,
    approximate_historical_ratios,
    build_historical_ratio_context,
    current_price_to_book,
    current_price_to_cfo,
    estimate_growth,
    estimate_growth_from_table,
    estimate_row,
    fcf_yield,
    growth_from_estimates,
    ratio_vs_history,
    ratio_vs_history_metric,
    statement_aligned_ratio_vs_history_metric,
    target_upside,
)

__all__ = [name for name in globals() if not name.startswith("_")]
